import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#181825"

[cursor]
style = "Block"
unfocused_hollow = true

[font]
normal = { family = "Maple Mono NF", style = "Regular" }
size = 10.0
