# Window Configuration
window:
  dimensions:
    columns: 130 
    lines: 38 
  padding:
    x: 10
    y: 10
  decorations: full

scrolling:
  history: 10000
  multiplier: 3

background_opacity: .98

# Font configuration
font:
  normal:
    family: Fira Code
    style: Retina
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic
  bold_italic:
    family: Fira Code 
    style: Bold Italic
  # Point size
  size: 12.0
  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0
  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyp_offset:
    x: 0
    y: 0
draw_bold_text_with_bright_colors: true

# Cursor Settings
cursor:
  style: Block
  unfocused_hollow: true
