# Enable flake8-bugbear (`B`) rules.
select = ["E", "F", "W"]

# Never enforce `E501` (line length violations).
ignore = ["F401"]

line-length = 120

# Ignore `E402` (import violations) in all `__init__.py` files, and in `path/to/file.py`.
[per-file-ignores]
"__init__.py" = ["E402"]
"path/to/file.py" = ["E402"]


