format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$conda\
$spack\
$aws\
$cmd_duration\
$line_break\
$character"""

[aws]
symbol = "aws "

[directory]
read_only = " 󰌾"
fish_style_pwd_dir_length = 3
truncation_length = 3
truncate_to_repo = false
truncation_symbol = "…/"

[git_branch]
symbol = " "
truncation_length = 20

[hostname]
ssh_symbol = "ssh "
