# Sets user-defined palette
palette = "catppuccin_mocha"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$conda\
$spack\
$aws\
$cmd_duration\
$line_break\
$character"""

[aws]
symbol = "aws "

[git_branch]
symbol = " "
truncation_length = 20

[hostname]
ssh_symbol = "ssh "

[spack]
truncation_length = 2

[character]
# Note the use of Catppuccin color 'maroon'
success_symbol = "[[♥](green)](maroon)"
error_symbol = "[❯](red)"

[directory]
fish_style_pwd_dir_length = 4
truncation_length = 4
truncation_symbol = "…/"
# Catppuccin 'lavender'
style = "bold lavender"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

