# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="half-life"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconfig="nvim ~/dotfiles/zsh/zshrc"
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias gs='git status'
alias cdc='cd /mnt/c/'
alias cd~='cd /mnt/c/Users/sahan'
alias cdd='cd /mnt/d/'
alias cde='cd /mnt/f/'
alias cdcode='cd ~/code'
alias fish_reload='source $HOME/.config/fish/config.fish'
alias nv='nvim'
alias vi='nvim'
alias em='emacs -nw'
alias ta='tmux a'
alias cgt='cargo nextest run'
alias cgr='cargo run'
alias cgb='cargo build'
export TERM=screen-256color
