# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.sources/sml/bin:$PATH
export PATH=$HOME/.sources/smlnj/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
export LIBGL_ALWAYS_SOFTWARE=true

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
unsetopt PROMPT_SP

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

export EDITOR="emacsclient -nw"

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
alias zshconf="$EDITOR ~/.zshrc"
alias zshsrc="source ~/.zshrc"
alias ohmyzsh="$EDITOR ~/.oh-my-zsh"
alias nvimconf="$EDITOR ~/.config/nvim/init.lua"

alias gs='git status'
alias gc='git commit'
alias ga='git add'
alias gp='git pull'
alias gP='git push'

alias cdc='cd /mnt/c/'
alias cd~='cd /mnt/c/Users/sahan'
alias cdd='cd /mnt/d/'
alias cde='cd /mnt/f/'
alias cdcode='cd ~/code'

alias fish_reload='source $HOME/.config/fish/config.fish'
alias nv='nvim'
alias vi='nvim'

alias ls='exa'
alias l='exa -lha'

alias em='emacsclient -nw'
alias emd='emacs --daemon'
alias emde='emacs --daemon && emacsclient -nw'
alias emdkill='emacsclient -e "(kill-emacs)"'
alias emdr='emacsclient -e "(kill-emacs)" && emacs --daemon'
alias emconf='emacsclient -nw ~/.emacs.d/config.org'
alias emreload='emacsclient -e "(load-file user-init-file)"'

alias cgt='cargo nextest run'
alias cgr='cargo run'
alias cgb='cargo build'

export TERM=xterm-256color

# opam configuration
[[ ! -r /home/sahana/.opam/opam-init/init.zsh ]] || source /home/sahana/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null

#[ -f "/home/sahana/.ghcup/env" ] && source "/home/sahana/.ghcup/env" # ghcup-env
[ -f "/home/sahana/.ghcup/env" ] && source "/home/sahana/.ghcup/env" # ghcup-env

# starship
eval "$(starship init zsh)"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniconda/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" ]; then
        . "/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh"
    else
        export PATH="/opt/homebrew/Caskroom/miniconda/base/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

